version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: reup_postgres
    restart: always
    environment:
      POSTGRES_DB: reup_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reup_network

volumes:
  postgres_data:

networks:
  reup_network:
    driver: bridge